version: '3'

vars:
  NAME: mandelbulb-generator
  RELEASE_BUILD: "false"
  RELEASE_PRESET: "ci-macos"

tasks:
  deps:
    dir: .
    cmds:
      - conan install . -s build_type=Debug -b missing -pr cpp23 -pr:b cpp23
      - conan install . -s build_type=Release -b missing -pr cpp23 -pr:b cpp23

  init:
    dir: .
    preconditions:
      - test -f CMakeUserPresets.json
    cmds:
      - cmake --preset=dev
      - cmake --preset={{.RELEASE_PRESET}} -DCMAKE_BUILD_TYPE=Release


  build:
    dir: .
    vars:
      CMAKE_SUFFIX: '{{if eq .RELEASE_BUILD "true"}}build --config Release{{else}}--preset=dev{{end}}'
    preconditions:
      - test -f CMakeUserPresets.json
    cmds:
      - cmake --build {{.CMAKE_SUFFIX}} -j 

  run:
    dir: .
    vars:
      PATH: '{{if eq .RELEASE_BUILD "true"}}build/{{.NAME}}{{else}}build/dev/{{.NAME}}{{end}}'
    cmds:
      - task: build
      - ./{{ .PATH }}

  fmt:
    dir: .
    cmds:
      - cmake -D FIX=YES -P cmake/lint.cmake
